### ISSUE TITLE
[BUG] TypeError: Cannot read property 'length' of undefined, in stdlib.js

### ISSUE THREAD

**Issue by aryx** [ocsigen/js_of_ocaml#1065]
I'm compiling a simple project using a few parsing libraries, and compilation works fine.
At runtime however even without any argument I get a javascript exception:

```
$ node _build/default/web/Simple_jsoo.bc.js -version
/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:566
          :i1 == 0 && s1.c.length == len?s1.c:s1.c.substr(i1,len);
                           ^

TypeError: Cannot read property 'length' of undefined
    at caml_blit_bytes (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:566:28)
    at caml_blit_string (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:582:7)
    at add_string (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:13329:7)
    at strput_acc (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:16327:19)
    at strput_acc (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:16329:40)
    at strput_acc (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:16326:12)
    at k$0 (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:17762:9)
    at caml_call1 (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:5909:28)
    at make_printf$0 (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:15646:16)
    at make_printf (/home/pad/github/semgrep/semgrep-core/_build/default/web/Simple_jsoo.bc.js:16013:30)

```
I have no idea what calls this code. Looking at the generated .js file it looks like it's part of stdlib.js.

**Expected behavior**
No exception

**Versions**
I'm using dune 2.7, and jsoo 3.6.0

**Comment by aryx** [comment]
and OCaml 4.09

**Comment by aryx** [comment]
I've opam pin the latest js_of_ocaml (3.8.0+git-09d573124 ) and I have the same problem with it.

**Comment by hhugo** [comment]
What are you dependencies ? Do you have custom javascript runtime ? Can you provide a reproduction case ?

**Comment by aryx** [comment]
It seems to come from my dependency to ounit2

and especially this line:
let shardf = Printf.sprintf "%s#%02d" (Unix.gethostname ())
at
https://github.com/gildor478/ounit/blob/84086bd161e400a99e5cb9cf14b2eabb19ad32de/src/lib/ounit2/advanced/oUnitUtils.ml#L223

In fact because of that dependency, I had to provide a fake unix_gethostname
// used by ounit2 library at the toplevel (grrr)
//Provides: unix_gethostname
function unix_gethostname(_cc) {
    console.log("here");
    return "";
}

that I've added in my dune file via the (javascript_files foo.js) stanza.

If I install ounit from scratch, and replace the call to Unix.gethostname() by a constant string, then
I don't get the TypeError anymore.

**Comment by hhugo** [comment]
your implementation of unix_gethostname is not correct, it returns a javascript string but it should return an ocaml one.
 ```javascript

// used by ounit2 library at the toplevel (grrr)
//Provides: unix_gethostname
//Requires: caml_string_of_jsbytes
function unix_gethostname(_cc) {
  return caml_string_of_jsbytes("hostname");
}
```

**Comment by aryx** [comment]
Oh, thx a lot!
