### ISSUE TITLE
Using Url module breaks node compatibility

### ISSUE THREAD

**Issue by little-arhat** [ocsigen/js_of_ocaml#442]
When using Url module (directly, or indirectly, say via `Jsonp` module), node can't load generated file, due to error:

```javascript
> var core = require('./resources/js/core.js')
TypeError: Cannot read property 'hostname' of undefined
    at /Users/u/prj/resources/js/core.js:2216:20
    at Object.<anonymous> (/Users/u/prj/resources/js/core.js:2276:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at repl:1:12
    at REPLServer.defaultEval (repl.js:260:27)
```

Offending code is:

```var aa=T.location,it=aa.hostname```

Note, that to trigger error code doesn't even have to call any of the `Jsonp` or `Url` functions, the mere link to it causes `js_of_ocaml` generate code that is using `window.location` on the top-level.

While I understand that `Jsonp` and probably `Url` don't make much sense outside browser, it's very useful to have node compatibility to testing/REPLing. 

Is there a way to overcome this issue maybe by some sort of tricks?

**Comment by little-arhat** [comment]
Steps to reproduce:

* `echo "let () = let _ = Jsonp.call in ()" > bug.ml`
* `ocamlfind ocamlc -linkpkg -package js_of_ocaml -o bug.byte bug.ml`
* `js_of_ocaml --pretty --noinline bug.byte -o bug.js`
