### ISSUE TITLE
Missing parentheses around "-1" in generated code

### ISSUE THREAD

**Issue by mlasson** [ocsigen/js_of_ocaml#507]
Hello !

Here is a way to reproduce the bug (I have not tested on the trunk version, only on 2.8.1): 

````
~$ cat main.ml 
let () =
  let r = ref 0.0 in
  for _ = 1 to 100 do
    r := !r -. (-1.0) *. !r;
  done;
  Printf.printf "%f\n%!" !r

~$ ocamlfind ocamlc -package js_of_ocaml main.ml -o main.byte && js_of_ocaml --pretty main.byte && nodejs main.js 

/home/mlasson/main.js:2665
     {var _bW_=_bU_--1*_bU_,_bX_=_bV_+1|0;
                     ^
SyntaxError: Unexpected number
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
````

-- 
Marc.

**Comment by hhugo** [comment]
Thanks a lot for the report. fixed now on master

**Comment by mlasson** [comment]
Thank you !
